name: ci

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python (3.12)
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install external libraries and dependencies
        run: make deps
      - name: Check source code issues
        run: make check
  test:
    needs: check
    runs-on: ${{ matrix.os }}
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10', '3.11', '3.12']
        include:
          - os: macos-latest
            python-version: '3.12'
          - os: windows-latest
            python-version: '3.12'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python (${{ matrix.os }}, ${{ matrix.python-version }})
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install external libraries and dependencies
        run: make deps
      - name: Run tests
        run: make test
      - name: Post coverage report
        if: env.CODECOV_TOKEN != '' && matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12'
        uses: codecov/codecov-action@v2
        with:
          token: ${{ env.CODECOV_TOKEN }}
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
  release:
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python (3.12)
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install external libraries and dependencies
        run: make deps
      - name: Create release if new version
        if: env.GITHUB_TOKEN != ''
        run: python scripts/gh_release.py
