name: publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python (3.12)
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install external libraries and dependencies
        run: make deps
      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel
      - name: Publish to PyPI
        if: env.PYPI_API_TOKEN != ''
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ env.PYPI_API_TOKEN }}
          skip_existing: true
          verbose: true
